language: python
sudo: false

env:
  global:
    - OFFICIAL_REPO="pcdshub/pmgr"

matrix:
  include:
    - python: 3.6
      env:
         - PCDS_CHANNEL=pcds-tag
    - python: 3.6
      env:
         - PCDS_CHANNEL=pcds-dev

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda install conda-build anaconda-client
  - conda update -q conda conda-build
  - conda config --add channels pcds-tag
  - conda config --add channels $PCDS_CHANNEL
  - conda config --append channels conda-forge
  # Useful for debugging any issues with conda
  - conda info -a

script:
  # We're actually *only* testing the conda build here.
  # This should be moved to the install section
  # and automated tests should be added below... eventually.
  - conda build conda-recipe --python $TRAVIS_PYTHON_VERSION --output-folder bld-dir

after_success:
  - |
    if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_REPO_SLUG == $OFFICIAL_REPO && $TRAVIS_BRANCH == $TRAVIS_TAG  && $TRAVIS_TAG != '' && $PCDS_CHANNEL == 'pcds-tag' ]]; then
      export ANACONDA_API_TOKEN=$CONDA_UPLOAD_TOKEN_TAG
      anaconda upload bld-dir/linux-64/*.tar.bz2
    fi
  - |
    if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_REPO_SLUG == $OFFICIAL_REPO && $TRAVIS_BRANCH == 'master' && $TRAVIS_TAG == '' && $PCDS_CHANNEL == 'pcds-dev' ]]; then
      export ANACONDA_API_TOKEN=$CONDA_UPLOAD_TOKEN_DEV
      anaconda upload bld-dir/linux-64/*.tar.bz2
    fi
